const propertyData = [
  {
    img: 'https://images.unsplash.com/photo-1515263487990-61b07816b324',
    name: 'Property 1',
    desc: 'This is the description for property number 1.',
    rent: 12000,
    location: 'Dubai Marina, Dubai, UAE',
    amenities: [
      'Private Pool',
      'Gymnasium',
      'Spa',
      'Garden',
      '24/7 Security',
      'Parking Space',
      'Terrace with Marina view',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1460317442991-0ec209397118',
    name: 'Property 2',
    desc: 'This is the description for property number 2.',
    rent: 8000,
    location: 'Downtown Dubai, Dubai, UAE',
    amenities: [
      'Gym',
      'Swimming Pool',
      'Concierge Service',
      'Balcony with City View',
      'Parking',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00',
    name: 'Property 3',
    desc: 'This is the description for property number 3.',
    rent: 12000,
    location: 'Dubai Marina, Dubai, UAE',
    amenities: [
      'Private Pool',
      'Gymnasium',
      'Spa',
      'Garden',
      '24/7 Security',
      'Parking Space',
      'Terrace with Marina view',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994',
    name: 'Property 4',
    desc: 'This is the description for property number 4.',
    rent: 8000,
    location: 'Downtown Dubai, Dubai, UAE',
    amenities: [
      'Gym',
      'Swimming Pool',
      'Concierge Service',
      'Balcony with City View',
      'Parking',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
    name: 'Property 5',
    desc: 'This is the description for property number 5.',
    rent: 15000,
    location: 'Jumeirah, Dubai, UAE',
    amenities: [
      'Private Beach Access',
      'Spacious Balcony',
      'Fitness Center',
      'Security',
      'Parking',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c',
    name: 'Property 6',
    desc: 'This is the description for property number 6.',
    rent: 18000,
    location: 'Dubai Marina, Dubai, UAE',
    amenities: [
      'Rooftop Pool',
      'Jacuzzi',
      'Fitness Center',
      'Concierge',
      'Parking',
      'Balcony',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1598228723793-52759bba239c',
    name: 'Property 7',
    desc: 'This is the description for property number 7.',
    rent: 25000,
    location: 'Emirates Hills, Dubai, UAE',
    amenities: [
      'Private Garden',
      'Swimming Pool',
      'Gym',
      'Maids Room',
      'Security',
    ],
  },
  {
    img: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09',
    name: 'Property 8',
    desc: 'This is the description for property number 8.',
    rent: 10000,
    location: 'Business Bay, Dubai, UAE',
    amenities: [
      'Fitness Center',
      'Swimming Pool',
      'Concierge',
      'Balcony',
      'Parking',
    ],
  },
]

export default propertyData
